apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multitool
  name: multitool
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: backend
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: frontend
        env:
          - name: HTTP_PORT
            value: "8080"
        
